Модальные окна для главной страницы
htmlacademy-htmlcss/960263-technomart-30 pull request #13
Opened 2021-02-21 18:33 UTC by AMenyakin

Модальные окна для главной страницы

2021-02-21 19:27 UTC, PolinaShneider requested changes
Переполнение — почти везде ок. У модалок странную багу нашла. Проверь, плиз, воспроизводится ли у тебя. И один коммент про кроссбраузерность оставила.

2021-02-21 19:27 UTC, PolinaShneider commented on index.html
> +        style="border: none" width="943" height="442" allowfullscreen
Через нормальный CSS без инлайна не обойтись? В демке показывали пример
![image](https://user-images.githubusercontent.com/15448200/108635760-34834f00-7492-11eb-8603-0faae57b3b7f.png)

2021-02-21 19:27 UTC, PolinaShneider commented on css/style.css
> +  display: none;
Когда я убираю `display: none` у модалок, чтобы посмотреть их, они у меня проваливаются куда-то :D Надо бы пофиксить

![image](https://user-images.githubusercontent.com/15448200/108635950-46192680-7493-11eb-8d56-425fe59192a0.png)

2021-02-22 09:11 UTC, AMenyakin commented on catalog.html
> +                  <div class="product-price-wrap">
Я хотел сделать, чтобы при переполнении текст обрезался и в конце появлялись 3 точки, без этой обёртки у меня еще и уголок справа скрывался, тот что через псевдоэлемент ::before сделан. Происходит это видимо из-за того, что мы элементу задаём overflow hidden, чтобы text-overflow: ellipsis сработал. Поэтому пришлось добавить дополнительную обертку, псевдоэлемент добавить к ней, а логику с обрезанием текста перенести во вложенный элемент.

2021-02-22 09:28 UTC, AMenyakin commented on css/style.css
> +.feedback-name::placeholder,
Только что проверил в Mozilla Firefox - всё норм. Судя по информации с сайта caniuse.com, этот селектор уже давно поддерживается теми браузерами, под которые мы верстаем. Ну а если рассматривать совсем старые версии браузеров, то тут уже не только к placeholder придётся префиксы добавлять, но и много где еще. В этой статье видимо речь как раз о поддержке очень старых версий, поэтому, возможно, не имеет смысла добавлять все эти префиксы. Как считаешь?

2021-02-22 09:34 UTC, AMenyakin commented on catalog.html
>                  <div class="price-controls">
Сделал в svg, не стал ужимать её, всё-таки логотип должен быть идеального качества, я считаю :))

2021-02-22 09:47 UTC, AMenyakin commented on index.html
>              <ul class="services-list list">
Точно, не учёл здесь момент с переполнением

2021-02-22 09:49 UTC, AMenyakin commented on css/style.css
> +  display: none;
Очень странный баг, а в каком браузере воспроизводится? Я тестил в Хроме и Firefox - всё хорошо было

2021-02-22 09:59 UTC, PolinaShneider commented on catalog.html
> +                  <div class="product-price-wrap">
В таком случае обертка оправдана 👍🏼

2021-02-22 10:05 UTC, PolinaShneider commented on css/style.css
> +.feedback-name::placeholder,
Не, старые точно не надо. Критерии требуют поддержку последних версий Chrome, Firefox, Safari. Если работает без префиксов, то вообще отлично

2021-02-22 10:44 UTC, merged