Доступность разметки главной страницы
htmlacademy-htmlcss/960263-technomart-30 pull request #15
Opened 2021-02-23 08:25 UTC by AMenyakin

Доступность разметки главной страницы

2021-02-23 22:44 UTC, PolinaShneider requested changes
Вижу, ты круто постарался по JS 👍🏼
На GitHub Pages отваливаются картинки в слайдере — фиксится заменой пути на относительный + пару комментов по JS оставила. Так как курс по верстке, что из них исправлять, а что нет — на твое усмотрение

2021-02-23 22:44 UTC, PolinaShneider commented on catalog.html
> +                      <img src="img/products/bosch-bfg-6000.jpg" alt="" width="144" height="128">
Атрибут alt сделал пустой строкой, потому что он частично дублировал h4?

2021-02-23 22:44 UTC, PolinaShneider commented on css/style.css
> +  background-position: center center;
Можно написать center один раз, и оно задастся для обоих осей

2021-02-23 22:44 UTC, PolinaShneider commented on js/product-slider.js
> +      this.slider.style['background-image'] = `url(${slide.backgroundUrl})`;
У тебя в слайдере картинки отвалились. Сделай путь относительным, добавив точку в начале (см второй скриншот), и все ок станет.

![image](https://user-images.githubusercontent.com/15448200/108915623-34c04d80-763e-11eb-96b7-98e382d065e0.png)
![image](https://user-images.githubusercontent.com/15448200/108915688-4efa2b80-763e-11eb-8f0e-1eed6754b46f.png)

2021-02-23 22:44 UTC, PolinaShneider commented on js/product-slider.js
> +(
У нас курс не по JS, но комменты оставлю. Исправлять или нет — на твое усмотрение

2021-02-23 22:44 UTC, PolinaShneider commented on js/product-slider.js
> +(
Для замыкания лучше будет смотреться классический вариант IIFE (immediately invoked function expression): https://learn.javascript.ru/closure#iife

То есть

```
(function() {

  // вся твоя инкапсулированная логика

})();
```

2021-02-23 22:44 UTC, PolinaShneider commented on js/product-slider.js
> +        const liElement = document.createElement('li');
Код с 41 по 49 строчку можно вынести в отдельную функцию

2021-02-23 22:44 UTC, PolinaShneider commented on js/product-slider.js
> +    ProductSlider.prototype.init = function() {
Ты смешиваешь функциональный и прототипный подход, и у меня возникло ощущение сумбура какое-то. Если хочешь, можешь посмотреть в сторону [классов](https://learn.javascript.ru/class). Выйдет даже лаконичнее.

2021-02-23 22:44 UTC, PolinaShneider commented on js/service-slider.js
> +      button.addEventListener('click', () => {
Исправлять не нужно, но почитай про делегирование: https://learn.javascript.ru/event-delegation
Чтобы не вешать обработчики в цикле, а повесить один на родителя

2021-02-23 22:44 UTC, PolinaShneider commented on js/modal.js
> +    modalFeedback.offsetWidth = modalFeedback.offsetWidth;
А что за кейс, и что за проблему этот трюк решает? Курс не по JS, но больно странно выглядит

2021-02-23 22:44 UTC, PolinaShneider commented on js/modal.js
> +  if (evt.code === 'Escape' || evt.keyCode === 27) {
Лучше писать код в стиле
```
if (!condition) {
  return
}
...
```

То есть инвертировать условие и выходить из функции как можно раньше, чтобы уменьшить вложенность: https://learn.javascript.ru/coding-style#urovni-vlozhennosti

2021-02-24 07:05 UTC, AMenyakin commented on catalog.html
> +                      <img src="img/products/bosch-bfg-6000.jpg" alt="" width="144" height="128">
Да, он тут избыточен вроде как.

2021-02-24 07:09 UTC, AMenyakin commented on js/product-slider.js
> +(
Так у меня как раз IIFE и есть, либо я что-то не так понял

2021-02-24 07:29 UTC, AMenyakin commented on js/modal.js
> +    modalFeedback.offsetWidth = modalFeedback.offsetWidth;
Делает так, чтобы анимация могла повторно воспроизводиться, подробнее можно здесь узнать - https://up.htmlacademy.ru/htmlcss/30/demos/4795#30 , там еще ссылка на статью, где более детально описывается этот трюк, я пока особо не вникал.

2021-02-24 10:46 UTC, PolinaShneider commented on js/product-slider.js
> +(
Сори, из-за форматирования не сразу опознала. Все гуд 👍🏼

2021-02-28 18:30 UTC, merged