Задание 2 - Разметка главной страницы
htmlacademy-htmlcss/960263-technomart-30 pull request #2
Opened 2021-01-23 14:07 UTC by AMenyakin

Сделал разметку главной страницы

2021-01-23 21:27 UTC, PolinaShneider requested changes
Верстка хорошая. Есть минорные замечания и пара вопросов

2021-01-23 21:27 UTC, PolinaShneider commented on index.html
> +        <h1>Интернет-магазин строительных материалов и инструментов</h1>
Можешь обосновать, почему это h1? Выглядит как описание, то есть p. Я бы добавила h1 "Техномарт", и визуально скрыла бы его. Так мы сможем соблюсти семантику

2021-01-23 21:27 UTC, PolinaShneider commented on index.html
> +        <a href="tel:+78125550555">+7 (812) 555-05-55</a>
Круто, что правильно размечаешь ссылки телефонов 👍🏼

2021-01-23 21:27 UTC, PolinaShneider commented on index.html
> +            <h3>Материалы</h3>
Лично для меня спорно. Я бы не размечала здесь заголовками. Но ошибки нет — вполне можно оставить так.

2021-01-23 21:27 UTC, PolinaShneider commented on index.html
> +          <article>
Тоже тег довольно спорный. Даже специально погуглила его использование (ресурс от [академии](https://htmlacademy.ru/courses/299/run/9), кстати). Можешь оставить, но я бы использовала просто div.

2021-01-23 21:27 UTC, PolinaShneider commented on index.html
> +            <article>
Мне кажется, без тега article здесь вполне можно обойтись. Одного li хватит. Семантика — это здорово, но конкретно в данном случае уже лишняя обертка получается.

2021-01-23 21:27 UTC, PolinaShneider commented on index.html
> +          <br>
Смотри, по поводу br следующий пойнт. Ими лучше не злоупотреблять. Если забегать далеко вперед и говорить об адаптивной верстке (не в рамках этого интенсива), они тебе потом выйдет боком. Текст под нужную ширину можно подогнать при помощи max-width на этапе стилизации. И уже в конце, если стилизация не поможет достичь нужного эффекта, можно будет парочку br добавить.

2021-01-23 21:27 UTC, PolinaShneider commented on index.html
> +          <br>
И кстати глянь критерий: https://up.htmlacademy.ru/htmlcss/30/criteries#b4

2021-01-24 07:18 UTC, AMenyakin commented on index.html
> +        <h1>Интернет-магазин строительных материалов и инструментов</h1>
Согласен, ошибся. Вынес h1 в main, а здесь применил тег p.

2021-01-24 07:19 UTC, AMenyakin commented on index.html
> +        <a href="tel:+78125550555">+7 (812) 555-05-55</a>
спасибо :)

2021-01-24 07:22 UTC, AMenyakin commented on index.html
> +            <h3>Материалы</h3>
Оставил так, по-моему вполне логично наименования категорий обернуть в теги h, плюс Вадим Макеев во втором лайве в проекте барбершоп делал аналогичную разметку, где в разделе преимуществ заключал каждое преимущество в h3, тут прямо аналогичная ситуация на мой взгляд.

2021-01-24 07:31 UTC, AMenyakin commented on index.html
> +          <article>
В этой статье очень мало примеров применения тега article, я думаю их недостаточно, чтобы действительно было понятно, подходит ли он здесь или нет. Если отталкиваться от фразы из этой статьи "тег <article>, который обозначает цельный, законченный и самостоятельный фрагмент информации", то этот блок как раз заслуживает того, чтобы его заключили в article. Плюс Вадим Макеев во втором лайве говорил, что карточки товаров тоже в article можно заключить. По сути этот слайдер очень похож на карточку товара. В общем исходя из всего вышеперечисленного, я больше всё таки склоняюсь к article, поэтому решил оставить его.

2021-01-24 07:32 UTC, AMenyakin commented on index.html
> +          <br>
Понял, спасибо.

2021-01-24 07:32 UTC, AMenyakin commented on index.html
> +            <article>
Согласен, лишняя обертка получилась.

2021-01-24 10:06 UTC, merged