Стилизация главной страницы
htmlacademy-htmlcss/960263-technomart-30 pull request #5
Opened 2021-01-30 18:44 UTC by AMenyakin

2021-01-30 23:14 UTC, PolinaShneider requested changes
По неймингу все ок. 

Основные моменты:
- где-то ты делаешь ту же работу, что и в normalize
- указание font-style (не отрицаю, что кое-где без него не обойтись)
- кастомные свойства, они же CSS-переменные — пройдись по ним еще раз и проверь, что нигде не ссылаешься на старые названия до переименования

Ну и минорные мелочи. Для домашки по стилизации результат очень даже неплохой

2021-01-30 23:14 UTC, PolinaShneider commented on css/style.css
> +  background-color: var(--silver);
Кажется, здесь больше подойдет `rgba(197,197,197,.3)`. И фокус тоже другой. 

Беру hex из макета, перегоняю в rgb, например, [здесь](https://www.rgbtohex.net/hextorgb/). Хотя быстрее в браузере это сделать. 

И ставлю нужную opacity по стайлгайду
![image](https://user-images.githubusercontent.com/15448200/106370172-87bd2280-6368-11eb-85d6-ad62b40d9f47.png)

2021-01-30 23:14 UTC, PolinaShneider commented on css/style.css
> +  background-color: var(--silver-chalice);
У тебя фокус без opacity тут (см коммент выше)

2021-01-31 16:19 UTC, AMenyakin commented on css/style.css
> +.visually-hidden:not(:focus):not(:active) {
Нам на лекции рассказывали только про сам подход визуального скрытия элементов для доступности, про реализацию я вычитал из статей. Если говорить коротно, то чтобы людям с ограниченными возможностями было удобнее пользоваться сайтом, были придуманы так называемые "skip navigation" ссылки, при переходе по которым, страница прокручивается к контенту. Проблема таких ссылок была в том, что ограниченному пользователю это удобно, а неограниченному это не нужно. Чтобы решить эту проблему, придумали подход с визуальным скрытием ссылки. Но если её скрыть, то пользователь, который например видит, но не может пользоваться мышкой, работая только с клавиатуры при нажатии tab не увидит эту ссылку и не поймет, что есть такая возможность, не нажимать 50 раз tab, а перейти сразу к контенту. Для этого придумали показывать ссылку, когда она становится в фокусе. То есть, если ты добавишь этот класс ссылке, она скроется, но на ней можно будет сфокусироваться через tab, при этом она станет видимой. Реализация взята [отсюда ](https://allyjs.io/tutorials/hiding-elements.html), более подробно про подход с такими ссылками можно узнать [тут](https://webaim.org/techniques/skipnav/)

2021-01-31 16:27 UTC, AMenyakin commented on css/style.css
> +  margin: 0;
Согласен, да, но ребята в демке делают именно так и я думаю, что это не спроста. Может это для подстраховки, если вдруг normalize.css по какой-то причине не загрузится, не знаю. Вот [ссылка](https://up.htmlacademy.ru/htmlcss/30/demos/4813#5) на демку, тут тоже сначала подключили normalize, а потом добавили эти стили.

2021-01-31 16:31 UTC, AMenyakin commented on css/style.css
> +  padding: 0;
Возможно, в каких-то браузерах есть padding, я даже не знаю. Но в демке на академии добавляют padding тоже, видимо в этом есть смысл, поэтому я тоже добавил по примеру.

2021-01-31 16:33 UTC, AMenyakin commented on css/style.css
> +.red-button {
Да, похоже, что тут имелось в виду состяоние focus.

2021-01-31 16:37 UTC, AMenyakin commented on css/style.css
> +  --translucent-white-a: rgba(255, 255, 255, 0.3);
На самом деле в этом именовании нет какого-то логического смысла, можно было вместо a b c написать 1 2 3, но мне не очень хотелось мешать буквы с цифрами, поэтому решил сделать так. Можно конечно обойтись без этого, но придётся сидеть и ломать голову, как это всё обозвать, а времени и так не хватает, к сожалению, поэтому не стал замарачиваться, решил задать такие имена.

2021-01-31 16:38 UTC, AMenyakin commented on css/style.css
> +  color: var(--translucent-white);
Точно, забыл переименовать здесь.

2021-01-31 17:06 UTC, AMenyakin commented on css/style.css
> +  height: 38px;
Пока так оставлю, если что, позже переделаю.

2021-01-31 20:24 UTC, PolinaShneider commented on css/style.css
> +.visually-hidden:not(:focus):not(:active) {
Ого, интересный подход — не слышала о таком

2021-01-31 20:29 UTC, merged