Стилизация страницы каталога
htmlacademy-htmlcss/960263-technomart-30 pull request #6
Opened 2021-02-01 19:25 UTC by AMenyakin

2021-02-01 21:07 UTC, PolinaShneider requested changes
Почти все ок — нужно буквально пару мелочей поправить

2021-02-01 21:07 UTC, PolinaShneider commented on catalog.html
> +            <li class="social-button"><a href="#">VK</a></li>
Немного беда с цветом текста в разных состояниях. Будет круто, если цвет текста на кнопках сделаешь, как в стайлгайде. Но можно пока эти ссылки не трогать. Все равно на этапе работе с декоративными элементами заменишь текст на иконки.

![image](https://user-images.githubusercontent.com/15448200/106517500-a4cd2f00-64e9-11eb-92ae-28e4530999f6.png)

2021-02-01 21:07 UTC, PolinaShneider commented on css/style.css
> +.sort-direction input[checked] label {
Не ошибка, но можно писать еще просто `input:checked`

2021-02-02 14:50 UTC, AMenyakin commented on css/style.css
> +  outline: none;
Я вроде бы этот класс сделал не только для ссылок, а еще и для элементов button, у которых есть outline. А убрал его из-за того, что у кнопок и ссылок предусмотрены стили на focus.

2021-02-02 15:44 UTC, merged