Сетка на флексах для главной страницы
htmlacademy-htmlcss/960263-technomart-30 pull request #9
Opened 2021-02-06 14:26 UTC by AMenyakin

2021-02-06 19:59 UTC, PolinaShneider requested changes
По использованию флексов — все гуд. Пара замечаний по форматированию и использованию `br`.

Ты что используешь для Pixel Perfect, кстати? Помимо того расширения для браузера, что вам советовали, есть очень классный встроенный PP в Zeplin (скриншот — как pixel perfect в нем найти). А у Zeplin есть классная [интеграция](https://www.figma.com/community/plugin/745330164019088593/Zeplin) с фигма. Тулза бесплатная, и очень рекомендую попробовать, если раньше с ней дела не имел

![image](https://user-images.githubusercontent.com/15448200/107128445-d7eb3600-68ce-11eb-9a92-b5588db8ad9e.png)

2021-02-06 19:59 UTC, PolinaShneider commented on catalog.html
>              <img src="img/logo-technomart.svg" alt="Техномарт" width="108" height="18">
Вроде svg, а смотрится как-то мутно и размыто (лого и в хедере, и в футере). Глянешь, что с ним не так?

![image](https://user-images.githubusercontent.com/15448200/107127381-c56cfe80-68c6-11eb-9207-672d2d187518.png)

2021-02-06 19:59 UTC, PolinaShneider commented on index.html
> +          <a class="button category-button" href="#">на любой вкус</a>
Карточки товаров пока не будешь верстать (без картинок)? Как по мне, это тоже сетка

2021-02-06 19:59 UTC, PolinaShneider commented on index.html
> +                Ведь мы неплохо заработаем,<br>
Не заметила этот момент раньше. Здесь точно br, а не отдельные параграфы? https://up.htmlacademy.ru/htmlcss/30/criteries#b4

2021-02-06 19:59 UTC, PolinaShneider commented on index.html
> +              <li class="service-item"><button type="button">Гарантия</button></li>
Общее пожелание по форматированию: давай делать переносы строк для вложенных тегов — так верстка будет читабельнее

```
<li class="service-item">
  <button type="button">Гарантия</button>
</li>
```

2021-02-06 19:59 UTC, PolinaShneider commented on index.html
> +              Настоящий мужской шоппинг начинается здесь! Огромный выбор товаров для<br>
Мне казалось, или ты убирал `<br>`? Очень желательно обходиться без него. Частично проблему переносов решит задание сетки. `br` используем только в крайних случаях

2021-02-06 19:59 UTC, PolinaShneider commented on index.html
> +            <a class="logo"><img src="img/footer-logo-technomart.png" alt="Техномарт" width="138" height="23"></a>
Здесь тоже два тега на одной строке. Пройдись, плиз, по верстке, и проверь этот момент

2021-02-06 19:59 UTC, PolinaShneider commented on index.html
>            <nav class="main-navigation">
Меню у тебя не совсем по сетке

![image](https://user-images.githubusercontent.com/15448200/107128223-1da6ff00-68cd-11eb-9afe-d016c57417ad.png)

2021-02-06 19:59 UTC, PolinaShneider commented on index.html
>                <a class="header-phone-link" href="tel:+78125550555">+7 (812) 555-05-55</a>
То ли текст в макете поменяли, то ли еще что. 

Интернет-магазин строительных материалов и инструментов **для ремонта**

![image](https://user-images.githubusercontent.com/15448200/107128250-534be800-68cd-11eb-9104-ec35817b32a6.png)

2021-02-06 19:59 UTC, PolinaShneider commented on index.html
>        <div class="footer-bottom-bar">
Что-то с нижней частью футера в плане pixel-perfect. Немного едет уровень фона и текст

![image](https://user-images.githubusercontent.com/15448200/107128293-a02fbe80-68cd-11eb-81ed-2243288d58d3.png)

2021-02-06 20:10 UTC, merged

2021-02-06 20:19 UTC, AMenyakin commented on catalog.html
>              <img src="img/logo-technomart.svg" alt="Техномарт" width="108" height="18">
это страница каталога, я там всё переделал уже, другая картинка теперь

2021-02-08 20:58 UTC, AMenyakin commented on index.html
> +                Ведь мы неплохо заработаем,<br>
По идее это всё - один параграф, просто разбитый на строки, поэтому применил тут <br>.

2021-02-08 21:05 UTC, AMenyakin commented on index.html
> +              Настоящий мужской шоппинг начинается здесь! Огромный выбор товаров для<br>
Да, тут согласен, перебор :))